import type { IdeaExample, LiveApp } from "./types";

export const liveApps: LiveApp[] = [
  {
    id: "shipfast",
    name: "ShipFast",
    url: "https://shipfa.st",
    tagline: "A Next.js boilerplate to ship SaaS in days, not months.",
    description:
      "Opinionated Next.js starter with Stripe, auth, emails, a database, and the UI pieces used to launch dozens of indie startups.",
    category: "Boilerplate",
    tags: [
      "next.js",
      "nextjs",
      "boilerplate",
      "starter",
      "saas",
      "stripe",
      "auth",
      "emails",
      "ship",
      "template",
      "javascript",
      "typescript",
    ],
    sourceId: "indie-products",
    maker: "ShipFast",
    year: 2023,
    featured: true,
    gap: "Vertical kits (agencies, clinics, marketplaces) are still thin. A niche ShipFast is an open lane.",
  },
  {
    id: "codefast",
    name: "CodeFast",
    url: "https://codefa.st",
    tagline: "Learn to code in weeks, built for founders who want to ship.",
    description:
      "A coding course aimed at non-technical founders who want to build their own SaaS instead of hiring a team on day one.",
    category: "Education",
    tags: [
      "course",
      "learn",
      "coding",
      "javascript",
      "next.js",
      "founders",
      "bootcamp",
      "tutorial",
    ],
    sourceId: "indie-products",
    maker: "CodeFast",
    year: 2024,
    featured: true,
    gap: "Domain-specific coding paths (AI agents, mobile, Shopify) are less crowded than general web.",
  },
  {
    id: "datafast",
    name: "DataFast",
    url: "https://datafa.st",
    tagline: "Startup analytics that show which channels actually bring paying users.",
    description:
      "Marketing analytics for indie founders. Connects revenue to traffic sources so you can see which tweets, ads, and pages convert.",
    category: "Analytics",
    tags: [
      "analytics",
      "marketing",
      "attribution",
      "revenue",
      "traffic",
      "startup",
      "indie",
      "dashboard",
      "conversion",
      "tracking",
    ],
    sourceId: "indie-products",
    maker: "DataFast",
    year: 2024,
    featured: true,
    gap: "Product analytics (funnels, feature usage) is still owned by PostHog and Mixpanel. A tiny usage layer on top of DataFast is open.",
  },
  {
    id: "trustmrr",
    name: "TrustMRR",
    url: "https://trustmrr.com",
    tagline: "Buy and sell startups with Stripe-verified revenue.",
    description:
      "A marketplace of startups with revenue verified against Stripe. Listings, founder profiles, and acquisition deal flow.",
    category: "Marketplace",
    tags: [
      "marketplace",
      "acquire",
      "acquisition",
      "buy",
      "sell",
      "startup",
      "revenue",
      "mrr",
      "stripe",
      "verified",
      "directory",
    ],
    sourceId: "indie-products",
    maker: "TrustMRR",
    year: 2025,
    featured: true,
    gap: "Vertical marketplaces (AI tools only, newsletters only, Shopify stores) are still fragmented.",
  },
  {
    id: "indiepage",
    name: "Indie Page",
    url: "https://indiepa.ge",
    tagline: "A personal homepage for indie makers and their products.",
    description:
      "Link-in-bio for builders: list your products, revenue, and socials on one page that looks like a maker, not a creator.",
    category: "Landing pages",
    tags: [
      "landing",
      "portfolio",
      "personal",
      "link in bio",
      "makers",
      "indie",
      "homepage",
      "directory",
    ],
    sourceId: "indie-products",
    maker: "Indie Page",
    year: 2023,
    featured: true,
    gap: "Team pages, studio sites, and investor-facing maker CVs are still mostly custom.",
  },
  {
    id: "zenvoice",
    name: "ZenVoice",
    url: "https://zenvoice.io",
    tagline: "Invoicing for freelancers who want less accounting.",
    description:
      "Simple invoicing, payment collection, and reminders aimed at solo freelancers instead of full accounting suites.",
    category: "Finance",
    tags: [
      "invoice",
      "invoicing",
      "freelance",
      "billing",
      "payments",
      "accounting",
      "stripe",
    ],
    sourceId: "indie-products",
    maker: "ZenVoice",
    year: 2023,
    gap: "Industry-specific invoicing (contractors, clinics, agencies with retainers) is still a wedge.",
  },
  {
    id: "byedispute",
    name: "ByeDispute",
    url: "https://byedispute.com",
    tagline: "Prevent Stripe chargebacks before they hit your account.",
    description:
      "A no-code layer that helps Stripe businesses reduce disputes with evidence, alerts, and prevention flows.",
    category: "Payments",
    tags: [
      "stripe",
      "chargeback",
      "dispute",
      "payments",
      "fraud",
      "prevention",
      "saas",
    ],
    sourceId: "indie-products",
    maker: "ByeDispute",
    year: 2024,
    gap: "Chargeback tools for platforms (marketplaces, marketplaces-of-one) still feel generic.",
  },
  {
    id: "launchviral",
    name: "LaunchViral",
    url: "https://launchvir.al",
    tagline: "Launch marketing for indie products that need a first spike.",
    description:
      "Playbooks and distribution help for Product Hunt, directories, and first-week launch traffic.",
    category: "Growth",
    tags: [
      "launch",
      "product hunt",
      "marketing",
      "growth",
      "directories",
      "viral",
      "distribution",
    ],
    sourceId: "indie-products",
    maker: "LaunchViral",
    year: 2024,
    gap: "Ongoing distribution (week 8, not week 1) is still the harder, less-served problem.",
  },
  {
    id: "habitsgarden",
    name: "Habits Garden",
    url: "https://habitsgarden.com",
    tagline: "A habit tracker that feels like growing a garden.",
    description:
      "Habit tracking with a garden metaphor instead of a streak calendar. Built as a small consumer habit product rather than a productivity suite.",
    category: "Consumer",
    tags: [
      "habit",
      "habits",
      "tracker",
      "garden",
      "streak",
      "wellness",
      "productivity",
    ],
    sourceId: "indie-products",
    maker: "Habits Garden",
    year: 2022,
    featured: true,
    gap: "Shared gardens, couples, and team rituals are still underserved versus solo streaks.",
  },
  {
    id: "logofast",
    name: "LogoFast",
    url: "https://logofa.st",
    tagline: "Generate a startup logo in seconds.",
    description:
      "Fast logo generation for founders who need something shippable before they hire a designer.",
    category: "Design",
    tags: ["logo", "branding", "generator", "ai", "design", "startup"],
    sourceId: "indie-products",
    maker: "LogoFast",
    year: 2023,
    gap: "Full brand kits (domain, color, pitch deck, socials) from one prompt are still messy.",
  },
  {
    id: "workbookpdf",
    name: "WorkbookPDF",
    url: "https://workbookpdf.com",
    tagline: "Turn lessons into fillable PDF workbooks.",
    description:
      "Create PDF workbooks for courses and coaching without a design tool.",
    category: "Education",
    tags: ["pdf", "workbook", "course", "coaching", "education", "download"],
    sourceId: "indie-products",
    maker: "WorkbookPDF",
    gap: "Interactive web workbooks (not PDFs) for cohorts remain a cleaner UX.",
  },
  {
    id: "poopup",
    name: "PoopUp",
    url: "https://poopup.co",
    tagline: "Website popups that convert without looking spammy.",
    description:
      "A lightweight popup tool for indie sites — waitlists, discounts, and lead capture.",
    category: "Growth",
    tags: ["popup", "waitlist", "leads", "conversion", "website", "marketing"],
    sourceId: "indie-products",
    maker: "PoopUp",
    gap: "Popups that feel native to product-led onboarding (not marketing sites) are still rare.",
  },
  {
    id: "bioage",
    name: "BioAge",
    url: "https://bioa.ge",
    tagline: "Estimate biological age from simple inputs.",
    description:
      "A consumer health micro-product that estimates biological age and related metrics.",
    category: "Health",
    tags: ["health", "age", "wellness", "bio", "consumer", "quiz"],
    sourceId: "indie-products",
    maker: "BioAge",
    gap: "Clinician-grade longevity dashboards are a different (and heavier) market.",
  },
  {
    id: "nomadlist",
    name: "Nomad List",
    url: "https://nomadlist.com",
    tagline: "Find the best cities for digital nomads.",
    description:
      "City rankings for remote workers: cost, internet, weather, safety, and a living community of nomads.",
    category: "Directory",
    tags: [
      "nomad",
      "remote",
      "cities",
      "travel",
      "directory",
      "cost of living",
      "coliving",
    ],
    sourceId: "indie-products",
    maker: "Nomad List",
    year: 2014,
    featured: true,
    gap: "Employer-sponsored nomad programs and visa-ready city packs are still ad-hoc.",
  },
  {
    id: "remoteok",
    name: "Remote OK",
    url: "https://remoteok.com",
    tagline: "The largest remote job board on the internet.",
    description:
      "Remote job listings across engineering, design, support, and more, with a public API and paid posts.",
    category: "Jobs",
    tags: ["jobs", "remote", "board", "hiring", "careers", "work"],
    sourceId: "indie-products",
    maker: "Remote OK",
    year: 2015,
    featured: true,
    gap: "Niche remote boards (climate, hardware, government) still outperform general boards for intent.",
  },
  {
    id: "photoai",
    name: "PhotoAI",
    url: "https://photoai.com",
    tagline: "AI photos of you, in any style, from a handful of selfies.",
    description:
      "Fine-tuned AI portraits and lifestyle photos generated from user selfies. One of the breakout indie AI products.",
    category: "AI images",
    tags: [
      "ai",
      "photos",
      "headshot",
      "portrait",
      "selfie",
      "avatars",
      "images",
      "generator",
    ],
    sourceId: "indie-products",
    maker: "PhotoAI",
    year: 2022,
    featured: true,
    gap: "Team libraries, brand-consistent product photos, and video avatars are still the next layer.",
  },
  {
    id: "interiorai",
    name: "InteriorAI",
    url: "https://interiorai.com",
    tagline: "Redesign any room with AI from a single photo.",
    description:
      "Upload a photo of a room and restyle it in different interior design aesthetics.",
    category: "AI images",
    tags: [
      "ai",
      "interior",
      "design",
      "room",
      "home",
      "architecture",
      "renovation",
    ],
    sourceId: "indie-products",
    maker: "InteriorAI",
    year: 2022,
    gap: "Contractor handoff (quotes, materials, local vendors) is the bigger adjacent product.",
  },
  {
    id: "hoodmaps",
    name: "Hoodmaps",
    url: "https://hoodmaps.com",
    tagline: "Crowd-drawn maps of what each neighborhood is actually like.",
    description:
      "Collaborative city maps labeled by locals — tourist, hipster, rich, industrial — used by travelers and movers.",
    category: "Maps",
    tags: ["maps", "neighborhoods", "cities", "travel", "crowd", "local"],
    sourceId: "indie-products",
    maker: "Hoodmaps",
    gap: "Safety-first and family-first layers on top of vibe maps are still underserved.",
  },
  {
    id: "headshotpro",
    name: "HeadshotPro",
    url: "https://www.headshotpro.com",
    tagline: "Professional AI headshots for teams, from selfies.",
    description:
      "Studio-quality AI headshots aimed at companies that need consistent portraits without a photoshoot.",
    category: "AI images",
    tags: [
      "ai",
      "headshot",
      "photos",
      "portrait",
      "linkedin",
      "teams",
      "hr",
      "selfie",
    ],
    sourceId: "indie-products",
    maker: "HeadshotPro",
    year: 2023,
    featured: true,
    gap: "Ongoing brand photo systems (new hires, refreshed looks, video) remain a service business.",
  },
  {
    id: "chatbase",
    name: "Chatbase",
    url: "https://www.chatbase.co",
    tagline: "Custom AI chatbots trained on your data.",
    description:
      "Build a support chatbot on your docs, site, and files. A bootstrapped AI support product with serious revenue.",
    category: "AI support",
    tags: [
      "ai",
      "chatbot",
      "support",
      "docs",
      "rag",
      "customer",
      "widget",
      "knowledge base",
    ],
    sourceId: "indie-products",
    maker: "Chatbase",
    year: 2023,
    featured: true,
    gap: "Chatbots that take action (refunds, bookings, CRM writes) are the next competitive layer.",
  },
  {
    id: "calcom",
    name: "Cal.com",
    url: "https://cal.com",
    tagline: "Open-source scheduling infrastructure.",
    description:
      "The open-source Calendly alternative. Embeddable booking, teams, workflows, and self-hosting.",
    category: "Scheduling",
    tags: [
      "calendar",
      "scheduling",
      "booking",
      "meetings",
      "calendly",
      "open source",
      "appointments",
    ],
    sourceId: "product-hunt",
    maker: "Cal.com",
    year: 2021,
    featured: true,
    gap: "Vertical booking (clinics, tutors, trades) with payments and forms still wins on UX.",
  },
  {
    id: "linear",
    name: "Linear",
    url: "https://linear.app",
    tagline: "Issue tracking built for high-performance teams.",
    description:
      "A fast project and issue tracker that replaced Jira for a generation of product teams.",
    category: "Productivity",
    tags: [
      "issues",
      "project",
      "tracker",
      "jira",
      "kanban",
      "roadmap",
      "engineering",
      "product",
    ],
    sourceId: "product-hunt",
    maker: "Linear",
    year: 2019,
    featured: true,
    gap: "Linear for non-engineering teams (content, legal, hardware) is still a wedge.",
  },
  {
    id: "dub",
    name: "Dub",
    url: "https://dub.co",
    tagline: "Link management for modern marketing teams.",
    description:
      "Branded short links, QR codes, and click analytics. An open-source Bitly alternative.",
    category: "Growth",
    tags: [
      "links",
      "shortener",
      "bitly",
      "qr",
      "analytics",
      "marketing",
      "open source",
    ],
    sourceId: "indie-products",
    maker: "Dub",
    year: 2022,
    featured: true,
    gap: "Deep product-led attribution (link → signup → paid) still overlaps with analytics tools.",
  },
  {
    id: "resend",
    name: "Resend",
    url: "https://resend.com",
    tagline: "Email for developers.",
    description:
      "Transactional email API with a React email toolchain. The modern SendGrid alternative.",
    category: "Email",
    tags: [
      "email",
      "transactional",
      "api",
      "developers",
      "sendgrid",
      "smtp",
      "react",
    ],
    sourceId: "product-hunt",
    maker: "Resend",
    year: 2023,
    gap: "Deliverability consulting bundled with the API is still mostly agencies.",
  },
  {
    id: "loops",
    name: "Loops",
    url: "https://loops.so",
    tagline: "Email for SaaS companies.",
    description:
      "Simple product-led email: onboarding, newsletters, and transactional sends without a marketing-cloud UI.",
    category: "Email",
    tags: ["email", "saas", "onboarding", "newsletter", "marketing", "loops"],
    sourceId: "indie-products",
    maker: "Loops",
    year: 2022,
    gap: "Lifecycle email that is truly designed around product events is still painful.",
  },
  {
    id: "plausible",
    name: "Plausible",
    url: "https://plausible.io",
    tagline: "Simple, privacy-friendly Google Analytics alternative.",
    description:
      "Lightweight web analytics with no cookies and a tiny script. Open source and EU-hosted.",
    category: "Analytics",
    tags: [
      "analytics",
      "privacy",
      "google analytics",
      "web",
      "open source",
      "cookies",
      "tracking",
    ],
    sourceId: "indie-hackers",
    maker: "Plausible",
    year: 2019,
    gap: "Privacy analytics with revenue attribution is the overlap with DataFast.",
  },
  {
    id: "posthog",
    name: "PostHog",
    url: "https://posthog.com",
    tagline: "Product analytics, session replay, and feature flags in one.",
    description:
      "Open-source product OS: events, funnels, recordings, experiments, and flags.",
    category: "Analytics",
    tags: [
      "analytics",
      "product",
      "session replay",
      "feature flags",
      "funnels",
      "open source",
      "events",
    ],
    sourceId: "product-hunt",
    maker: "PostHog",
    year: 2020,
    gap: "Opinionated, tiny PostHog for the first 1,000 users is still a positioning opportunity.",
  },
  {
    id: "tally",
    name: "Tally",
    url: "https://tally.so",
    tagline: "The simplest way to create forms.",
    description:
      "Free-form builder that feels like Notion. Unlimited forms on the free plan.",
    category: "Forms",
    tags: ["forms", "surveys", "typeform", "notion", "waitlist", "quiz"],
    sourceId: "product-hunt",
    maker: "Tally",
    year: 2020,
    gap: "Forms that are also a CRM for a specific industry still beat general builders.",
  },
  {
    id: "beehiiv",
    name: "beehiiv",
    url: "https://www.beehiiv.com",
    tagline: "The newsletter platform built for growth.",
    description:
      "Write, monetize, and grow a newsletter with referrals, ads, and recommendations.",
    category: "Newsletters",
    tags: [
      "newsletter",
      "substack",
      "email",
      "writing",
      "audience",
      "publish",
      "media",
    ],
    sourceId: "product-hunt",
    maker: "beehiiv",
    year: 2021,
    gap: "Niche paid newsletters with community (not just email) still feel like a different product.",
  },
  {
    id: "framer",
    name: "Framer",
    url: "https://www.framer.com",
    tagline: "Design and publish a production site on a canvas.",
    description:
      "A design tool that ships real websites. Used by startups for marketing sites without a handoff.",
    category: "Landing pages",
    tags: [
      "website",
      "landing",
      "design",
      "no-code",
      "cms",
      "marketing site",
      "webflow",
    ],
    sourceId: "product-hunt",
    maker: "Framer",
    year: 2021,
    gap: "App-like sites with auth and payments still leave Framer for custom code.",
  },
  {
    id: "carrd",
    name: "Carrd",
    url: "https://carrd.co",
    tagline: "Simple, free, fully responsive one-page sites.",
    description:
      "The default one-pager for indie launches, waitlists, and personal links.",
    category: "Landing pages",
    tags: ["landing", "one page", "waitlist", "personal", "no-code", "website"],
    sourceId: "indie-hackers",
    maker: "Carrd",
    year: 2015,
    gap: "Carrd with built-in payments and email is still a pile of integrations.",
  },
  {
    id: "supabase",
    name: "Supabase",
    url: "https://supabase.com",
    tagline: "Open-source Firebase alternative.",
    description:
      "Postgres, auth, storage, and edge functions. The default backend for a lot of indie SaaS.",
    category: "Backend",
    tags: [
      "backend",
      "database",
      "postgres",
      "auth",
      "firebase",
      "open source",
      "storage",
    ],
    sourceId: "product-hunt",
    maker: "Supabase",
    year: 2020,
    gap: "Vertical backends (multiplayer, billing-native, HIPAA) still justify wrapping Supabase.",
  },
  {
    id: "clerk",
    name: "Clerk",
    url: "https://clerk.com",
    tagline: "Authentication and user management for React apps.",
    description:
      "Drop-in auth, organizations, and billing-aware user management used by a lot of Next.js apps.",
    category: "Auth",
    tags: ["auth", "authentication", "users", "react", "next.js", "organizations"],
    sourceId: "product-hunt",
    maker: "Clerk",
    year: 2020,
    gap: "Auth that is also your customer portal (invoices, usage, seats) is still stitched together.",
  },
  {
    id: "polar",
    name: "Polar",
    url: "https://polar.sh",
    tagline: "Monetize your software, from open source to SaaS.",
    description:
      "Merchant of record for indie software: subscriptions, one-time buys, and GitHub-native funding.",
    category: "Payments",
    tags: [
      "payments",
      "merchant of record",
      "open source",
      "subscriptions",
      "lemon squeezy",
      "stripe",
    ],
    sourceId: "indie-products",
    maker: "Polar",
    year: 2023,
    gap: "Usage-based billing UX for tiny products is still harder than it should be.",
  },
  {
    id: "lemonsqueezy",
    name: "Lemon Squeezy",
    url: "https://www.lemonsqueezy.com",
    tagline: "Payments, tax, and subscriptions as merchant of record.",
    description:
      "Sell digital products and SaaS globally without becoming a tax expert.",
    category: "Payments",
    tags: [
      "payments",
      "merchant of record",
      "digital products",
      "subscriptions",
      "tax",
      "gumroad",
    ],
    sourceId: "product-hunt",
    maker: "Lemon Squeezy",
    year: 2021,
    gap: "Creator-commerce with community access (courses + Discord + billing) is still a glue job.",
  },
  {
    id: "gumroad",
    name: "Gumroad",
    url: "https://gumroad.com",
    tagline: "Sell stuff. Digital products, memberships, and more.",
    description:
      "The original indie checkout for ebooks, files, and creator products.",
    category: "Payments",
    tags: ["digital products", "creators", "checkout", "ebooks", "memberships", "sell"],
    sourceId: "indie-hackers",
    maker: "Gumroad",
    year: 2011,
    gap: "Gumroad-like simplicity with SaaS seats and usage is Polar / LS territory.",
  },
  {
    id: "raycast",
    name: "Raycast",
    url: "https://www.raycast.com",
    tagline: "The macOS launcher that replaced Spotlight for builders.",
    description:
      "Extensible launcher with snippets, windows, AI, and a store of productivity commands.",
    category: "Productivity",
    tags: ["launcher", "macos", "spotlight", "productivity", "snippets", "ai"],
    sourceId: "product-hunt",
    maker: "Raycast",
    year: 2020,
    gap: "Team launchers (shared commands, runbooks) are still early.",
  },
  {
    id: "obsidian",
    name: "Obsidian",
    url: "https://obsidian.md",
    tagline: "A private knowledge base that works on local Markdown files.",
    description:
      "Linked-note app for people who want a graph, plugins, and files they actually own.",
    category: "Notes",
    tags: [
      "notes",
      "knowledge",
      "markdown",
      "pkm",
      "second brain",
      "wiki",
      "local",
    ],
    sourceId: "indie-hackers",
    maker: "Obsidian",
    year: 2020,
    gap: "Opinionated PKM for a job (sales, research, legal) beats general graphs.",
  },
  {
    id: "loom",
    name: "Loom",
    url: "https://www.loom.com",
    tagline: "Record your screen and camera in a shareable video.",
    description:
      "Async video for product updates, bug reports, and customer conversations.",
    category: "Video",
    tags: ["video", "screen recording", "async", "camera", "meetings", "loom"],
    sourceId: "product-hunt",
    maker: "Loom",
    year: 2016,
    gap: "Loom that auto-files into Linear / Notion with action items is still a Zap.",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    url: "https://elevenlabs.io",
    tagline: "AI voice: TTS, cloning, and agents.",
    description:
      "High-quality AI speech used for audiobooks, agents, and content production.",
    category: "AI audio",
    tags: ["ai", "voice", "tts", "audio", "cloning", "speech", "agents"],
    sourceId: "product-hunt",
    maker: "ElevenLabs",
    year: 2022,
    gap: "Voice agents that do a specific job (collections, onboarding calls) beat general TTS.",
  },
  {
    id: "crisp",
    name: "Crisp",
    url: "https://crisp.chat",
    tagline: "Customer messaging for startups.",
    description:
      "Live chat, inbox, knowledge base, and a chatbot — a lighter Intercom.",
    category: "Support",
    tags: ["chat", "support", "inbox", "intercom", "helpdesk", "widget"],
    sourceId: "indie-hackers",
    maker: "Crisp",
    year: 2016,
    gap: "Support that lives inside the product UI (not a bubble) is still custom.",
  },
  {
    id: "typefully",
    name: "Typefully",
    url: "https://typefully.com",
    tagline: "Write, schedule, and grow on X / Twitter.",
    description:
      "A writing room for tweets and threads with analytics and scheduling.",
    category: "Social",
    tags: ["twitter", "x", "threads", "scheduling", "writing", "social", "growth"],
    sourceId: "indie-products",
    maker: "Typefully",
    year: 2021,
    gap: "Cross-network writing (X + LinkedIn + newsletter) from one draft is still clunky.",
  },
  {
    id: "kit",
    name: "Kit",
    url: "https://kit.com",
    tagline: "Creator-first email marketing (formerly ConvertKit).",
    description:
      "Email marketing, recommendations, and commerce for writers and creators.",
    category: "Email",
    tags: ["email", "creators", "newsletter", "marketing", "convertkit"],
    sourceId: "indie-hackers",
    maker: "Kit",
    year: 2013,
    gap: "Kit-like simplicity for B2B product-led email is why Loops exists.",
  },
  {
    id: "acquire",
    name: "Acquire.com",
    url: "https://acquire.com",
    tagline: "Buy and sell startups.",
    description:
      "A marketplace for acquiring internet businesses, with listings, NDAs, and deal rooms.",
    category: "Marketplace",
    tags: [
      "marketplace",
      "acquire",
      "buy",
      "sell",
      "startup",
      "acquisition",
      "microacquire",
    ],
    sourceId: "directories",
    maker: "Acquire.com",
    year: 2020,
    gap: "Verified-revenue positioning is why TrustMRR showed up next to it.",
  },
  {
    id: "alternativeto",
    name: "AlternativeTo",
    url: "https://alternativeto.net",
    tagline: "Crowdsourced software recommendations.",
    description:
      "Find apps similar to the ones you already know. A long-running software directory.",
    category: "Directory",
    tags: ["directory", "alternatives", "software", "comparison", "apps"],
    sourceId: "directories",
    maker: "AlternativeTo",
    year: 2009,
    gap: "Idea-first search (describe a product, get live twins) is the Appkin lane.",
  },
  {
    id: "lovable",
    name: "Lovable",
    url: "https://lovable.dev",
    tagline: "Build apps by chatting with AI.",
    description:
      "An AI app builder that turns prompts into working full-stack software.",
    category: "AI builders",
    tags: ["ai", "builder", "no-code", "full-stack", "prompt", "apps", "codegen"],
    sourceId: "product-hunt",
    maker: "Lovable",
    year: 2024,
    featured: true,
    gap: "Builders that start from a live-competitor scan (not a blank prompt) are missing.",
  },
  {
    id: "v0",
    name: "v0",
    url: "https://v0.dev",
    tagline: "Generate UI with shadcn from a prompt.",
    description:
      "Vercel's generative UI tool. Describe an interface, get React you can ship.",
    category: "AI builders",
    tags: ["ai", "ui", "react", "shadcn", "vercel", "frontend", "codegen"],
    sourceId: "product-hunt",
    maker: "Vercel",
    year: 2023,
    gap: "v0 does UI. The product decision (should this exist?) still happens elsewhere.",
  },
  {
    id: "makerkit",
    name: "MakerKit",
    url: "https://makerkit.dev",
    tagline: "SaaS starter kits for Next.js and more.",
    description:
      "Production SaaS boilerplate with auth, billing, organizations, and a well-documented codebase.",
    category: "Boilerplate",
    tags: [
      "boilerplate",
      "saas",
      "next.js",
      "starter",
      "kit",
      "auth",
      "billing",
      "template",
    ],
    sourceId: "indie-products",
    maker: "MakerKit",
    year: 2022,
    gap: "Kits opinionated around one ICP (B2B AI, marketplaces) still differentiate.",
  },
  {
    id: "supastarter",
    name: "supastarter",
    url: "https://supastarter.dev",
    tagline: "Production-ready SaaS starter for Next.js + Supabase.",
    description:
      "A starter that combines Next.js, Supabase, billing, and i18n for shipping SaaS faster.",
    category: "Boilerplate",
    tags: [
      "boilerplate",
      "saas",
      "next.js",
      "supabase",
      "starter",
      "template",
      "billing",
    ],
    sourceId: "indie-products",
    maker: "supastarter",
    year: 2023,
    gap: "Starters that include a competitor-scan step in the README would be on-brand here.",
  },
  {
    id: "fillout",
    name: "Fillout",
    url: "https://www.fillout.com",
    tagline: "Powerful forms, surprisingly easy.",
    description:
      "Form builder with logic, payments, and integrations — a Typeform-class product with more depth.",
    category: "Forms",
    tags: ["forms", "typeform", "surveys", "payments", "quiz", "waitlist"],
    sourceId: "product-hunt",
    maker: "Fillout",
    year: 2022,
    gap: "Documents that are forms (contracts, onboarding PDFs) sit between Fillout and DocuSign.",
  },
];

export const ideaExamples: IdeaExample[] = [
  {
    label: "SaaS boilerplate",
    text: "A Next.js boilerplate with Stripe, auth, and emails so I can launch a SaaS this week.",
  },
  {
    label: "Founder analytics",
    text: "Analytics that show indie hackers which tweets and pages actually bring paying users.",
  },
  {
    label: "Startup marketplace",
    text: "A marketplace to buy and sell startups with Stripe-verified revenue.",
  },
  {
    label: "AI headshots",
    text: "An AI tool that generates professional headshots from a few selfies.",
  },
  {
    label: "Habit garden",
    text: "A habit tracker that feels like growing a garden instead of checking boxes.",
  },
];

export function getAppById(id: string) {
  return liveApps.find((app) => app.id === id);
}

export function featuredApps() {
  return liveApps.filter((app) => app.featured);
}

export function appsBySource(sourceId: LiveApp["sourceId"]) {
  return liveApps.filter((app) => app.sourceId === sourceId);
}

export function allCategories() {
  return Array.from(new Set(liveApps.map((app) => app.category))).sort();
}
